### PR TITLE
Aquatica style by Moobien

### PR DESCRIPTION
**Pull request by MotionlessTrain**
# Aquatica style by Moobien

## Description
This is a new underwater style, inspired by Subnautica.

## Version 1.1
- TH lvl 1 fixes
- lure guard lvl 1 fixes
- SS fixes
- TH anti flooding measures added to lvl 1 th mine
- Job specific tags for the lure guard tower

### CODE REVIEW

**Comment by Moobien** [comment]
merge merge merge....

**Comment by MotionlessTrain** [comment]
Don't forget that new styles need to be reviewed 😄

**Comment by someaddons** [comment]
I'm not sure if we should add it at all, since minecolonies currently does not support underwater styles

**Comment by MotionlessTrain** [comment]
> I'm not sure if we should add it at all, since minecolonies currently does not support underwater styles

It actually does. Aquatica has been playtested, and we already have an underwater style in Stylecolonies
(Underwater Base by McSassa)

**Comment by someaddons** [comment]
ye I'm sure you know better than me what the mod does support and what not lol :D

**Comment by MotionlessTrain** [comment]
> ye I'm sure you know better than me what the mod does support and what not lol :D

I mean, with that argument, I'm surprised that Underwater Base is part of Stylecolonies

**Comment by Moobien** [comment]
> ye I'm sure you know better than me what the mod does support and what not lol :D

wasn't the water clearing mechanic added to help players playing the underwater styles?

**Comment by MotionlessTrain** [comment]
^^

It has been supported more than it did already, as of late

**Pull request merged**
